# Input Settings: initialize base input folder names,
# dataset collections, and algorithms to run over
input_settings:

    # Directory for singularity images, absolute path
    sif_dir: "$(pwd)/images_singularity/"
    overlay_dir: "$(pwd)/images_singularity_overlay"

    # Base input directory
    input_dir : "inputs_beeline2"

    # Subdirectory of inputs that datasets are placed in
    dataset_dir: "L1"

    # Denotes a list of datasets, each with the following parameters:
    #   name: Name of the dataset. May be used in logging or other
    #       messages written during execution
    #
    #   exprData: scRNA-Seq expression data file. Cells are along the
    #            columns and genes are along the rows.
    #   cellData: a file containing pseudotime ordering, or any other 
    #             information about cells.
    #   trueEdges: Name of the refrence network file in the
    #              edge list format. Needed for evaluation.
    
    datasets:

        - name: "dream5_1"
          exprData: "ExpressionData.csv"
          cellData: "PseudoTime.csv"
          trueEdges: "refNetwork.csv"

        - name: "dream5_3"
          exprData: "ExpressionData.csv"
          cellData: "PseudoTime.csv"
          trueEdges: "refNetwork.csv"
          
        - name: "dream5_4"
          exprData: "ExpressionData.csv"
          cellData: "PseudoTime.csv"
          trueEdges: "refNetwork.csv"
          
        - name: "hESC"
          exprData: "ExpressionData.csv"
          cellData: "PseudoTime.csv"
          trueEdges: "refNetwork.csv"

        - name: "hHep"
          exprData: "ExpressionData.csv"
          cellData: "PseudoTime.csv"
          trueEdges: "refNetwork.csv"
          
        - name: "mESC"
          exprData: "ExpressionData.csv"
          cellData: "PseudoTime.csv"
          trueEdges: "refNetwork.csv"
          
        - name: "mDC"
          exprData: "ExpressionData.csv"
          cellData: "PseudoTime.csv"
          trueEdges: "refNetwork.csv"
          
        - name: "mHSC-E"
          exprData: "ExpressionData.csv"
          cellData: "PseudoTime.csv"
          trueEdges: "refNetwork.csv"          

        - name: "mHSC-GM"
          exprData: "ExpressionData.csv"
          cellData: "PseudoTime.csv"
          trueEdges: "refNetwork.csv"

        - name: "mHSC-L"
          exprData: "ExpressionData.csv"
          cellData: "PseudoTime.csv"
          trueEdges: "refNetwork.csv"             
  
 
    # Denotes a list of algorithms to run. Each has the following parameters:
    #   name: Name of the algorithm. Must be recognized by the pipeline, see
    #       code for acceptable values
    #
    #   should_run: whether or not to run the algorithm
    #
    #   params: any additional, algorithm-specific parameters
    #       should be specified in the params map for a given algorithm
    #
    
    
     
    
    algorithms:

        - name: "CICT"
          params: 
              should_run: [False]
              groundTruth: ['refNetwork.csv']
              edgeTypes: ['ewMImm,ewMIempirical,ewMIshrink ,efMIempirical, Pearson,,Kendall,Spearman,Euclidean,L10NormManhattan,Granger']  #  ewMImm,ewMIempirical, efMIshrink, efMImm, Pearson,Kendall,Spearman, Euclidean,Granger,
              supervised.positiveClass: ['c,rc']  # c:causal edges, 'c,rc': causal and reversecausal
              supervised.negativeClass: ['r']  # r:random edges, 'rc': reversecausal
              supervised.gtProp: [.2] #proportion of GT used for classification
              supervised.train: [.3] #proportion of classification records used for training
              fp.fn.cost: [1/5]  #False positive to False Negative cost ratio for threshold identification
              
              
        - name: "PIDC"
          params: 
              should_run: [True]


        - name: "GRNVBEM"
          params: 
              should_run: [False]  #should_run: [True]

              

        - name: "GENIE3"
          params: 
              should_run: [True]  #<===
              
              
              
        - name: "GRNBOOST2"
          params: 
              should_run: [True] #<===
              
              
        - name: "PPCOR"
          params: 
              should_run: [True]  #<====
              #should_run: [False]
              # p-value cutoff
              # Used in parsing output
              pVal: [0.01]
              
               
        - name: "SCODE"
          params:
              should_run: [False]  #<==== Error
                  #should_run: [False]
              z: [10]
              nIter: [1000]
              nRep: [6]

        - name: "SCNS"
          params: 
              should_run: [False] #<=== error
              
              
        - name: "SINCERITIES"
          params: 
              should_run: [False]  #<====Error
              nBins: [10]
              
              
        - name: "LEAP"
          params: 
              should_run: [False]
              #should_run: [False]
              # Default maxLag value is 0.33
              maxLag: [0.33]
             
              
        - name: "GRISLI"
          params: 
              should_run: [False]
              L: [10]
              R: [3000]
              alphaMin: [0.0]


        - name: "SINGE"
          params: 
              should_run: [False]
              lambda: [0.01]
              dT: [15]
              num_lags: [5]
              kernel_width: [0.5]
              prob_zero_removal: [0]
              prob_remove_samples: [0.0]
              family: ["gaussian"]
              num_replicates: [6]


        - name: "SCRIBE"
          params: 
              should_run: [False]
              ### required parameters
              # a list of delay values
              delay: ["5"]
              # any of 'RDI', 'uRDI', 'cRDI', or 'ucRDI'
              method: ['ucRDI']
              # lower detection limit (expression below this 
              # will be treated as zero.
              lowerDetectionLimit: [0]
              # expressionFamily: for synthetic data use uninormal
              #  for mRNA count data use negbinomial.size()
              expressionFamily: ['uninormal']
              ### optional but recommended parameters
              # log transform expression values or not
              log: [False]
              # ignore pseudotime values (and use experimental
              # time points instead), recommended True for synthetic data
              # False for real mRNA data
              ignorePT: [True]


# Output Settings: initialize base output folder names
output_settings:

    # Base output directory
    output_dir: "outputs"
    output_prefix: "L1"
